project:
  type: website

website:
  title: "Jin Hu-Health data analyst"
  navbar:
    left:
      - href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/Jiner-H
format:
  html:
    theme: sketchy
    css: styles.css



