project:
  type: website

website:
  title: "Jin Hu-Health data analyst"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Jiner-H
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css



